### ISSUE TITLE
child(path) method not working

### ISSUE THREAD

**Issue by Gloix** [forest-fire/firemock#3]
Whenever I want to use the `child` method of a snapshot I get null.
I think the problem lies within the `child` method, since it calls the lodash `get` method using the ordered dictionary, but with a normal object path.

Would it be better to call `convert.arrayToHash` before internally querying? I would consider this a good solution assuming `child` is not a common function to call...
Another option would be to have a cached version of the hash version of the data structure.

Finally it boils down to CPU vs RAM.

Test code:
https://runkit.com/embed/b51qgbxpveji
```
var {Mock} = require("firemock")
let database = new Mock({
    "key1": {
        "subkey1": "subval1"
    }
})
console.log(database.ref("key1").onceSync("value").child("subkey1"))
```

Btw, great library! 😀

**Comment by ksnyde** [comment]
Hey thanks and sorry for not noticing this issue until now. I will see if I can get this closed out this week.

**Comment by ksnyde** [comment]
Hi @Gloix are you still having problems with this ... sorry I've been so negligent with issues but we've had a ton of updates and wondering if you still are using or having an issue.

**Comment by Gloix** [comment]
Since `onceSync` is not in the API anymore I had to modify it to use `once` and it's working now.
